/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.springgen.springgen.AngularApp;
import org.xtext.example.springgen.springgen.Dockerfile;
import org.xtext.example.springgen.springgen.ProjectConfiguration;
import org.xtext.example.springgen.springgen.ProjectElement;
import org.xtext.example.springgen.springgen.SpringBootProject;
import org.xtext.example.springgen.springgen.SpringgenPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Spring Boot Project</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.impl.SpringBootProjectImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.impl.SpringBootProjectImpl#getConfiguration <em>Configuration</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.impl.SpringBootProjectImpl#getElements <em>Elements</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.impl.SpringBootProjectImpl#getDockerfile <em>Dockerfile</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.impl.SpringBootProjectImpl#getAngularApp <em>Angular App</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SpringBootProjectImpl extends MinimalEObjectImpl.Container implements SpringBootProject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getConfiguration() <em>Configuration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfiguration()
   * @generated
   * @ordered
   */
  protected ProjectConfiguration configuration;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<ProjectElement> elements;

  /**
   * The cached value of the '{@link #getDockerfile() <em>Dockerfile</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDockerfile()
   * @generated
   * @ordered
   */
  protected Dockerfile dockerfile;

  /**
   * The cached value of the '{@link #getAngularApp() <em>Angular App</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAngularApp()
   * @generated
   * @ordered
   */
  protected AngularApp angularApp;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpringBootProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpringgenPackage.Literals.SPRING_BOOT_PROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProjectConfiguration getConfiguration()
  {
    return configuration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConfiguration(ProjectConfiguration newConfiguration, NotificationChain msgs)
  {
    ProjectConfiguration oldConfiguration = configuration;
    configuration = newConfiguration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION, oldConfiguration, newConfiguration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConfiguration(ProjectConfiguration newConfiguration)
  {
    if (newConfiguration != configuration)
    {
      NotificationChain msgs = null;
      if (configuration != null)
        msgs = ((InternalEObject)configuration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION, null, msgs);
      if (newConfiguration != null)
        msgs = ((InternalEObject)newConfiguration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION, null, msgs);
      msgs = basicSetConfiguration(newConfiguration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION, newConfiguration, newConfiguration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProjectElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<ProjectElement>(ProjectElement.class, this, SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dockerfile getDockerfile()
  {
    return dockerfile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDockerfile(Dockerfile newDockerfile, NotificationChain msgs)
  {
    Dockerfile oldDockerfile = dockerfile;
    dockerfile = newDockerfile;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE, oldDockerfile, newDockerfile);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDockerfile(Dockerfile newDockerfile)
  {
    if (newDockerfile != dockerfile)
    {
      NotificationChain msgs = null;
      if (dockerfile != null)
        msgs = ((InternalEObject)dockerfile).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE, null, msgs);
      if (newDockerfile != null)
        msgs = ((InternalEObject)newDockerfile).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE, null, msgs);
      msgs = basicSetDockerfile(newDockerfile, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE, newDockerfile, newDockerfile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AngularApp getAngularApp()
  {
    return angularApp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAngularApp(AngularApp newAngularApp, NotificationChain msgs)
  {
    AngularApp oldAngularApp = angularApp;
    angularApp = newAngularApp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP, oldAngularApp, newAngularApp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAngularApp(AngularApp newAngularApp)
  {
    if (newAngularApp != angularApp)
    {
      NotificationChain msgs = null;
      if (angularApp != null)
        msgs = ((InternalEObject)angularApp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP, null, msgs);
      if (newAngularApp != null)
        msgs = ((InternalEObject)newAngularApp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP, null, msgs);
      msgs = basicSetAngularApp(newAngularApp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP, newAngularApp, newAngularApp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION:
        return basicSetConfiguration(null, msgs);
      case SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
      case SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE:
        return basicSetDockerfile(null, msgs);
      case SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP:
        return basicSetAngularApp(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SpringgenPackage.SPRING_BOOT_PROJECT__NAME:
        return getName();
      case SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION:
        return getConfiguration();
      case SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS:
        return getElements();
      case SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE:
        return getDockerfile();
      case SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP:
        return getAngularApp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SpringgenPackage.SPRING_BOOT_PROJECT__NAME:
        setName((String)newValue);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION:
        setConfiguration((ProjectConfiguration)newValue);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends ProjectElement>)newValue);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE:
        setDockerfile((Dockerfile)newValue);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP:
        setAngularApp((AngularApp)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SpringgenPackage.SPRING_BOOT_PROJECT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION:
        setConfiguration((ProjectConfiguration)null);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS:
        getElements().clear();
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE:
        setDockerfile((Dockerfile)null);
        return;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP:
        setAngularApp((AngularApp)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SpringgenPackage.SPRING_BOOT_PROJECT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SpringgenPackage.SPRING_BOOT_PROJECT__CONFIGURATION:
        return configuration != null;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ELEMENTS:
        return elements != null && !elements.isEmpty();
      case SpringgenPackage.SPRING_BOOT_PROJECT__DOCKERFILE:
        return dockerfile != null;
      case SpringgenPackage.SPRING_BOOT_PROJECT__ANGULAR_APP:
        return angularApp != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SpringBootProjectImpl
