/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.springgen.services.SpringGenGrammarAccess;

@SuppressWarnings("all")
public class SpringGenSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SpringGenGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Controller_Repository___ControllerKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_7___or___RepositoryKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_5__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SpringGenGrammarAccess) access;
		match_Controller_Repository___ControllerKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_7___or___RepositoryKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_5__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getControllerAccess().getControllerKeyword_0()), new TokenAlias(false, false, grammarAccess.getControllerAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getControllerAccess().getRightCurlyBracketKeyword_7())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getRepositoryAccess().getRepositoryKeyword_0()), new TokenAlias(false, false, grammarAccess.getRepositoryAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRepositoryAccess().getRightCurlyBracketKeyword_5())));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Controller_Repository___ControllerKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_7___or___RepositoryKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_5__.equals(syntax))
				emit_Controller_Repository___ControllerKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_7___or___RepositoryKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_5__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('controller' '{' '}') | ('repository' '{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_Controller_Repository___ControllerKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_7___or___RepositoryKeyword_0_LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_5__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
