/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SpringGenProposalProvider extends AbstractSpringGenProposalProvider {
}
