/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.springgen.generator;

import java.util.ArrayList;
import java.util.Objects;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.xtext.example.springgen.springgen.DTO;
import org.xtext.example.springgen.springgen.DatabaseConfiguration;
import org.xtext.example.springgen.springgen.Entity;
import org.xtext.example.springgen.springgen.Identifier;
import org.xtext.example.springgen.springgen.ListType;
import org.xtext.example.springgen.springgen.ParamTransfer;
import org.xtext.example.springgen.springgen.ProjectConfiguration;
import org.xtext.example.springgen.springgen.Property;
import org.xtext.example.springgen.springgen.RDBMS;
import org.xtext.example.springgen.springgen.Repository;
import org.xtext.example.springgen.springgen.ServerConfiguration;
import org.xtext.example.springgen.springgen.SetType;
import org.xtext.example.springgen.springgen.SpringBootProject;
import org.xtext.example.springgen.springgen.Type;
import org.xtext.example.springgen.springgen.ValueTypes;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SpringGenGenerator extends AbstractGenerator {
  @Override
  public void beforeGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
  }

  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof Entity)) {
        String _xifexpression = null;
        Identifier _identifier = ((Entity)element).getIdentifier();
        boolean _tripleNotEquals = (_identifier != null);
        if (_tripleNotEquals) {
          _xifexpression = this.extractValueType(((Entity)element).getIdentifier().getType().toString());
        } else {
          _xifexpression = "int";
        }
        final String idType = _xifexpression;
        String _xifexpression_1 = null;
        Identifier _identifier_1 = ((Entity)element).getIdentifier();
        boolean _tripleNotEquals_1 = (_identifier_1 != null);
        if (_tripleNotEquals_1) {
          _xifexpression_1 = ((Entity)element).getIdentifier().getName().toString();
        } else {
          _xifexpression_1 = "Id";
        }
        final String idName = _xifexpression_1;
        this.generateEntityClass(((Entity) element), fsa, input, idType, idName);
        Repository _repository = ((Entity)element).getRepository();
        boolean _tripleNotEquals_2 = (_repository != null);
        if (_tripleNotEquals_2) {
          this.generateRepository(((Entity)element), fsa, input, idType);
        }
        this.generateService(((Entity)element), fsa, input);
        this.generateController(((Entity)element), fsa, input);
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final Procedure1<EObject> _function_1 = (EObject element) -> {
      if ((element instanceof DTO)) {
        this.generateDtoClass(((DTO) element), fsa, input);
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function_1);
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function_2 = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function_2);
    final String projectName = projectNameHolder.get(0);
    final ArrayList<ProjectConfiguration> configHolder = new ArrayList<ProjectConfiguration>();
    final Procedure1<EObject> _function_3 = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        configHolder.add(((SpringBootProject)element).getConfiguration());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function_3);
    final ProjectConfiguration config = configHolder.get(0);
    this.generateMainClass(fsa, input, config);
    this.generateMavenFiles(fsa, input);
    this.generateTestFolder(fsa, input);
    if ((config != null)) {
      this.generatePropertiesFile(config, fsa);
      String _elvis = null;
      DatabaseConfiguration _database = config.getDatabase();
      RDBMS _type = null;
      if (_database!=null) {
        _type=_database.getType();
      }
      String _string = null;
      if (_type!=null) {
        _string=_type.toString();
      }
      if (_string != null) {
        _elvis = _string;
      } else {
        _elvis = "mysql";
      }
      final String dbmsType = _elvis;
      RDBMS _type_1 = config.getDatabase().getType();
      boolean _matched = false;
      if (Objects.equals(_type_1, "h2")) {
        _matched=true;
        this.generatePropertiesH2(config, fsa);
      }
      if (!_matched) {
        if (Objects.equals(_type_1, "oracle")) {
          _matched=true;
          this.generatePropertiesOracle(config, fsa);
        }
      }
      if (!_matched) {
        this.generatePropertiesFile(config, fsa);
      }
    }
    this.generatePomXml(config, fsa, projectName);
  }

  public void generateController(final Entity entity, final IFileSystemAccess2 fsa, final Resource input) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    final String className = entity.getName();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(".controllers;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import com.springboot.");
    _builder.append(projectName);
    _builder.append(".entities.");
    _builder.append(className);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import com.springboot.");
    _builder.append(projectName);
    _builder.append(".services.");
    String _firstUpper = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.append("import org.springframework.beans.factory.annotation.Autowired;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.*;");
    _builder.newLine();
    _builder.append("import java.util.*;");
    _builder.newLine();
    _builder.append("import org.springframework.http.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@RestController");
    _builder.newLine();
    _builder.append("@RequestMapping(\"");
    {
      String _baseUrl = entity.getController().getBaseUrl();
      boolean _tripleNotEquals = (_baseUrl != null);
      if (_tripleNotEquals) {
        String _baseUrl_1 = entity.getController().getBaseUrl();
        _builder.append(_baseUrl_1);
      } else {
        _builder.append("/api/");
        String _firstUpper_1 = StringExtensions.toFirstUpper(className);
        _builder.append(_firstUpper_1);
        _builder.append(" ");
      }
    }
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("public class ");
    String _firstUpper_2 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_2);
    _builder.append("Controller {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Autowired");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final ");
    String _firstUpper_3 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_3, "    ");
    _builder.append("Service ");
    String _firstLower = StringExtensions.toFirstLower(className);
    _builder.append(_firstLower, "    ");
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    {
      ParamTransfer _deleteParam = entity.getController().getDeleteParam();
      boolean _tripleNotEquals_1 = (_deleteParam != null);
      if (_tripleNotEquals_1) {
        String _generateDeleteMethodController = this.generateDeleteMethodController(entity);
        _builder.append(_generateDeleteMethodController, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    {
      ParamTransfer _findParam = entity.getController().getFindParam();
      boolean _tripleNotEquals_2 = (_findParam != null);
      if (_tripleNotEquals_2) {
        String _generateFindMethodController = this.generateFindMethodController(entity);
        _builder.append(_generateFindMethodController, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    {
      ParamTransfer _createParam = entity.getController().getCreateParam();
      boolean _tripleNotEquals_3 = (_createParam != null);
      if (_tripleNotEquals_3) {
        String _generateSaveMethodController = this.generateSaveMethodController(entity);
        _builder.append(_generateSaveMethodController, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GetMapping(\"/deleteAll\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<String> deleteAll");
    String _firstUpper_4 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_4, "    ");
    _builder.append("s() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ");
    String _firstLower_1 = StringExtensions.toFirstLower(className);
    _builder.append(_firstLower_1, "        ");
    _builder.append("Service.deleteAll");
    String _firstUpper_5 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_5, "        ");
    _builder.append("s();");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GetMapping(\"/findAll\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(className, "    ");
    _builder.append("> findAll");
    String _firstUpper_6 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_6, "    ");
    _builder.append("s() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ");
    String _firstLower_2 = StringExtensions.toFirstLower(className);
    _builder.append(_firstLower_2, "        ");
    _builder.append("Service.findAll");
    String _firstUpper_7 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_7, "        ");
    _builder.append("s();");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    final String content = _builder.toString();
    String _firstUpper_8 = StringExtensions.toFirstUpper(className);
    String _plus = ((("src/main/java/com/springboot/" + projectName) + "/controllers/") + _firstUpper_8);
    String _plus_1 = (_plus + "Controller.java");
    fsa.generateFile(_plus_1, content);
  }

  public void generateService(final Entity entity, final IFileSystemAccess2 fsa, final Resource input) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    final String className = entity.getName();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(".services;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import com.springboot.");
    _builder.append(projectName);
    _builder.append(".entities.");
    _builder.append(className);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import com.springboot.");
    _builder.append(projectName);
    _builder.append(".repositories.");
    _builder.append(className);
    _builder.append("Repository;");
    _builder.newLineIfNotEmpty();
    _builder.append("import org.springframework.beans.factory.annotation.Autowired;");
    _builder.newLine();
    _builder.append("import org.springframework.http.*;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.*;");
    _builder.newLine();
    _builder.append("import java.util.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class ");
    String _firstUpper = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper);
    _builder.append("Service {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Autowired");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final ");
    _builder.append(className, "    ");
    _builder.append("Repository ");
    _builder.append(className, "    ");
    _builder.append("Repo;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    {
      ParamTransfer _deleteParam = entity.getController().getDeleteParam();
      boolean _tripleNotEquals = (_deleteParam != null);
      if (_tripleNotEquals) {
        String _generateDeleteMethod = this.generateDeleteMethod(entity);
        _builder.append(_generateDeleteMethod, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    {
      ParamTransfer _findParam = entity.getController().getFindParam();
      boolean _tripleNotEquals_1 = (_findParam != null);
      if (_tripleNotEquals_1) {
        String _generateFindMethod = this.generateFindMethod(entity);
        _builder.append(_generateFindMethod, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    {
      ParamTransfer _createParam = entity.getController().getCreateParam();
      boolean _tripleNotEquals_2 = (_createParam != null);
      if (_tripleNotEquals_2) {
        String _generateSaveMethod = this.generateSaveMethod(entity);
        _builder.append(_generateSaveMethod, "    ");
        _builder.append(" ");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<String> deleteAll");
    String _firstUpper_1 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_1, "    ");
    _builder.append("s() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append(className, "        ");
    _builder.append("Repo.deleteAll");
    String _firstUpper_2 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_2, "        ");
    _builder.append("s();");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return new ResponseEntity<String>(\"all ");
    String _firstUpper_3 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_3, "        ");
    _builder.append(" was deleted from database\", null, HttpStatus.OK);");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(className, "    ");
    _builder.append("> findAll");
    String _firstUpper_4 = StringExtensions.toFirstUpper(className);
    _builder.append(_firstUpper_4, "    ");
    _builder.append("s() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ");
    _builder.append(className, "        ");
    _builder.append("Repo.findAll();");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    final String content = _builder.toString();
    String _firstUpper_5 = StringExtensions.toFirstUpper(className);
    String _plus = ((("src/main/java/com/springboot/" + projectName) + "/services/") + _firstUpper_5);
    String _plus_1 = (_plus + "Service.java");
    fsa.generateFile(_plus_1, content);
  }

  public String generateFindMethod(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("public ");
      String _name = entity.getName();
      _builder.append(_name);
      _builder.append(" find");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("( ");
      String _extractValueType = this.extractValueType(entity.getIdentifier().getType().toString());
      _builder.append(_extractValueType);
      _builder.append(" id) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("return ");
      String _name_1 = entity.getName();
      _builder.append(_name_1, "    ");
      _builder.append("Repo.findById(id);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String findContent = _builder.toString();
      _xblockexpression = findContent;
    }
    return _xblockexpression;
  }

  public String generateSaveMethod(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("public void save");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("( ");
      String _name = entity.getName();
      _builder.append(_name);
      _builder.append(" element) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      String _name_1 = entity.getName();
      _builder.append(_name_1, "    ");
      _builder.append("Repo.save(element);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String saveContent = _builder.toString();
      _xblockexpression = saveContent;
    }
    return _xblockexpression;
  }

  public String generateDeleteMethod(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("public ResponseEntity<String> delete");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("(");
      String _extractValueType = this.extractValueType(entity.getIdentifier().getType().toString());
      _builder.append(_extractValueType);
      _builder.append(" id ) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("if (");
      String _name = entity.getName();
      _builder.append(_name, "    ");
      _builder.append("Repo.isEmpty()) {");
      _builder.newLineIfNotEmpty();
      _builder.append("        ");
      _builder.append("return new ResponseEntity<String>(\"No ");
      String _firstUpper_1 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_1, "        ");
      _builder.append(" with this id \", null, HttpStatus.OK);");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("return new ResponseEntity<String>(\"");
      String _firstUpper_2 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_2, "    ");
      _builder.append(" deleted successfully\", null, HttpStatus.OK);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String deleteContent = _builder.toString();
      _xblockexpression = deleteContent;
    }
    return _xblockexpression;
  }

  public String generateFindMethodController(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("@GetMapping(\"/findById\")");
      _builder.newLine();
      _builder.append("public ");
      String _name = entity.getName();
      _builder.append(_name);
      _builder.append(" find");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("(@RequestParam ");
      String _extractValueType = this.extractValueType(entity.getIdentifier().getType().toString());
      _builder.append(_extractValueType);
      _builder.append(" id) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("return ");
      String _name_1 = entity.getName();
      _builder.append(_name_1, "    ");
      _builder.append("Service.find");
      String _firstUpper_1 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_1, "    ");
      _builder.append("(id);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String findContent = _builder.toString();
      _xblockexpression = findContent;
    }
    return _xblockexpression;
  }

  public String generateSaveMethodController(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("@PostMapping(\"save");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("\")");
      _builder.newLineIfNotEmpty();
      _builder.append("public ResponseEntity<String> save");
      String _firstUpper_1 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_1);
      _builder.append("(@RequestBody ");
      String _name = entity.getName();
      _builder.append(_name);
      _builder.append(" element) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("return ");
      String _name_1 = entity.getName();
      _builder.append(_name_1, "    ");
      _builder.append("Service.save(element);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String saveContent = _builder.toString();
      _xblockexpression = saveContent;
    }
    return _xblockexpression;
  }

  public String generateDeleteMethodController(final Entity entity) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("@DeleteMapping(\"/delete");
      String _firstUpper = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper);
      _builder.append("ById\")");
      _builder.newLineIfNotEmpty();
      _builder.append("public ResponseEntity<String> delete");
      String _firstUpper_1 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_1);
      _builder.append("(");
      String _extractValueType = this.extractValueType(entity.getIdentifier().getType().toString());
      _builder.append(_extractValueType);
      _builder.append(" id ) {");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("return ");
      String _firstUpper_2 = StringExtensions.toFirstUpper(entity.getName());
      _builder.append(_firstUpper_2, "    ");
      _builder.append("Repository.deleteById(id);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      final String deleteContent = _builder.toString();
      _xblockexpression = deleteContent;
    }
    return _xblockexpression;
  }

  public String getHibernateDialect(final String dbmsType) {
    if (dbmsType != null) {
      switch (dbmsType) {
        case "Mysql":
          return "org.hibernate.dialect.MySQL5Dialect";
        case "Postgres":
          return "org.hibernate.dialect.PostgreSQLDialect";
        case "Mariadb":
          return "org.hibernate.dialect.MariaDBDialect";
        case "h2":
          return "org.hibernate.dialect.H2Dialect";
        case "Oracle":
          return "org.hibernate.dialect.Oracle12cDialect";
        default:
          return "org.hibernate.dialect.MySQL5Dialect";
      }
    } else {
      return "org.hibernate.dialect.MySQL5Dialect";
    }
  }

  public void generatePomXml(final ProjectConfiguration config, final IFileSystemAccess2 fsa, final String prjName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<parent>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>spring-boot-starter-parent</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>2.5.0</version>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<relativePath/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</parent>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<groupId>com.springboot</groupId>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<artifactId>");
    _builder.append(prjName, "    ");
    _builder.append("</artifactId>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("<version>0.0.1-SNAPSHOT</version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<name>");
    _builder.append(prjName, "    ");
    _builder.append("</name>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("<description>Demo project for Spring Boot</description>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<java.version>17</java.version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</properties>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependencies>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-data-jpa</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-web</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.projectlombok</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>lombok</artifactId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<optional>true</optional>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-test</artifactId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<scope>test</scope>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    DatabaseConfiguration _database = config.getDatabase();
    RDBMS _type = null;
    if (_database!=null) {
      _type=_database.getType();
    }
    String _generateDatabaseDependencies = this.generateDatabaseDependencies(_type.toString());
    _builder.append(_generateDatabaseDependencies, "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("</dependencies>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<build>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<artifactId>spring-boot-maven-plugin</artifactId>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<excludes>");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<exclude>");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("<groupId>org.projectlombok</groupId>");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("<artifactId>lombok</artifactId>");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("</exclude>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("</excludes>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</build>");
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    final String pomContent = _builder.toString();
    fsa.generateFile("pom.xml", pomContent);
  }

  public String generateDatabaseDependencies(final String dbmsType) {
    if (dbmsType != null) {
      switch (dbmsType) {
        case "Mysql":
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("<dependency>");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("<groupId>com.mysql</groupId>");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("<artifactId>mysql-connector-j</artifactId>");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("<scope>runtime</scope>");
          _builder.newLine();
          _builder.append("</dependency>");
          _builder.newLine();
          return _builder.toString();
        case "Postgres":
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("<dependency>");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("<groupId>org.postgresql</groupId>");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("<artifactId>postgresql</artifactId>");
          _builder_1.newLine();
          _builder_1.append("    ");
          _builder_1.append("<scope>runtime</scope>");
          _builder_1.newLine();
          _builder_1.append("</dependency>");
          _builder_1.newLine();
          return _builder_1.toString();
        case "Mariadb":
          StringConcatenation _builder_2 = new StringConcatenation();
          _builder_2.append("<dependency>");
          _builder_2.newLine();
          _builder_2.append("    ");
          _builder_2.append("<groupId>org.mariadb.jdbc</groupId>");
          _builder_2.newLine();
          _builder_2.append("    ");
          _builder_2.append("<artifactId>mariadb-java-client</artifactId>");
          _builder_2.newLine();
          _builder_2.append("    ");
          _builder_2.append("<scope>runtime</scope>");
          _builder_2.newLine();
          _builder_2.append("</dependency>");
          _builder_2.newLine();
          return _builder_2.toString();
        case "Oracle":
          StringConcatenation _builder_3 = new StringConcatenation();
          _builder_3.append("<dependency>");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("<groupId>com.oracle.database.jdbc</groupId>");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("<artifactId>ojdbc11</artifactId>");
          _builder_3.newLine();
          _builder_3.append("    ");
          _builder_3.append("<scope>runtime</scope>");
          _builder_3.newLine();
          _builder_3.append("</dependency>");
          _builder_3.newLine();
          return _builder_3.toString();
        case "h2":
          StringConcatenation _builder_4 = new StringConcatenation();
          _builder_4.append("<dependency>");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("<groupId>com.h2database</groupId>");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("<artifactId>h2</artifactId>");
          _builder_4.newLine();
          _builder_4.append("    ");
          _builder_4.append("<scope>runtime</scope>");
          _builder_4.newLine();
          _builder_4.append("</dependency>");
          _builder_4.newLine();
          return _builder_4.toString();
        default:
          return "";
      }
    } else {
      return "";
    }
  }

  public void generatePropertiesH2(final ProjectConfiguration config, final IFileSystemAccess2 fsa) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Server Configuration");
    _builder.newLine();
    _builder.append("server.port = ");
    int _xifexpression = (int) 0;
    if ((Objects.equals(config.getServer(), null) || (config.getServer().getPort() == 0))) {
      _xifexpression = 8080;
    } else {
      _xifexpression = config.getServer().getPort();
    }
    _builder.append(_xifexpression);
    _builder.newLineIfNotEmpty();
    _builder.append("server.cpath = ");
    String _elvis = null;
    ServerConfiguration _server = config.getServer();
    String _contextPath = null;
    if (_server!=null) {
      _contextPath=_server.getContextPath();
    }
    if (_contextPath != null) {
      _elvis = _contextPath;
    } else {
      _elvis = "/api";
    }
    _builder.append(_elvis);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Database Configuration");
    _builder.newLine();
    _builder.append("spring.datasource.url = jdbc:");
    Object _elvis_1 = null;
    DatabaseConfiguration _database = config.getDatabase();
    RDBMS _type = null;
    if (_database!=null) {
      _type=_database.getType();
    }
    if (_type != null) {
      _elvis_1 = _type;
    } else {
      _elvis_1 = "h2";
    }
    _builder.append(_elvis_1);
    _builder.append(":mem:");
    String _elvis_2 = null;
    DatabaseConfiguration _database_1 = config.getDatabase();
    String _name = null;
    if (_database_1!=null) {
      _name=_database_1.getName();
    }
    if (_name != null) {
      _elvis_2 = _name;
    } else {
      _elvis_2 = "dbname";
    }
    _builder.append(_elvis_2);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.username = ");
    String _elvis_3 = null;
    DatabaseConfiguration _database_2 = config.getDatabase();
    String _username = null;
    if (_database_2!=null) {
      _username=_database_2.getUsername();
    }
    if (_username != null) {
      _elvis_3 = _username;
    } else {
      _elvis_3 = "root";
    }
    _builder.append(_elvis_3);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.password = ");
    String _elvis_4 = null;
    DatabaseConfiguration _database_3 = config.getDatabase();
    String _password = null;
    if (_database_3!=null) {
      _password=_database_3.getPassword();
    }
    if (_password != null) {
      _elvis_4 = _password;
    } else {
      _elvis_4 = "password";
    }
    _builder.append(_elvis_4);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Hibernate Configuration");
    _builder.newLine();
    _builder.append("spring.jpa.hibernate.ddl-auto = update");
    _builder.newLine();
    _builder.append("spring.jpa.show-sql = true");
    _builder.newLine();
    _builder.append("spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.");
    DatabaseConfiguration _database_4 = config.getDatabase();
    RDBMS _type_1 = null;
    if (_database_4!=null) {
      _type_1=_database_4.getType();
    }
    String _hibernateDialect = this.getHibernateDialect(_type_1.toString());
    _builder.append(_hibernateDialect);
    _builder.newLineIfNotEmpty();
    final String propertiesContent = _builder.toString();
    final String pomFilePath = "src/main/resources/application.properties";
    fsa.generateFile(pomFilePath, propertiesContent);
  }

  public void generatePropertiesOracle(final ProjectConfiguration config, final IFileSystemAccess2 fsa) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Server Configuration");
    _builder.newLine();
    _builder.append("server.port = ");
    int _xifexpression = (int) 0;
    if ((Objects.equals(config.getServer(), null) || (config.getServer().getPort() == 0))) {
      _xifexpression = 8080;
    } else {
      _xifexpression = config.getServer().getPort();
    }
    _builder.append(_xifexpression);
    _builder.newLineIfNotEmpty();
    _builder.append("server.cpath = ");
    String _elvis = null;
    ServerConfiguration _server = config.getServer();
    String _contextPath = null;
    if (_server!=null) {
      _contextPath=_server.getContextPath();
    }
    if (_contextPath != null) {
      _elvis = _contextPath;
    } else {
      _elvis = "/api";
    }
    _builder.append(_elvis);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Database Configuration");
    _builder.newLine();
    _builder.append("spring.datasource.url = jdbc:oracle:thin:@localhost:");
    int _xifexpression_1 = (int) 0;
    if ((Objects.equals(config.getDatabase(), null) || (config.getDatabase().getPort() == 0))) {
      _xifexpression_1 = 1521;
    } else {
      _xifexpression_1 = config.getDatabase().getPort();
    }
    _builder.append(_xifexpression_1);
    _builder.append("/");
    String _elvis_1 = null;
    DatabaseConfiguration _database = config.getDatabase();
    String _name = null;
    if (_database!=null) {
      _name=_database.getName();
    }
    if (_name != null) {
      _elvis_1 = _name;
    } else {
      _elvis_1 = "dbname";
    }
    _builder.append(_elvis_1);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.username = ");
    String _elvis_2 = null;
    DatabaseConfiguration _database_1 = config.getDatabase();
    String _username = null;
    if (_database_1!=null) {
      _username=_database_1.getUsername();
    }
    if (_username != null) {
      _elvis_2 = _username;
    } else {
      _elvis_2 = "root";
    }
    _builder.append(_elvis_2);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.password = ");
    String _elvis_3 = null;
    DatabaseConfiguration _database_2 = config.getDatabase();
    String _password = null;
    if (_database_2!=null) {
      _password=_database_2.getPassword();
    }
    if (_password != null) {
      _elvis_3 = _password;
    } else {
      _elvis_3 = "password";
    }
    _builder.append(_elvis_3);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Hibernate Configuration");
    _builder.newLine();
    _builder.append("spring.jpa.hibernate.ddl-auto = update");
    _builder.newLine();
    _builder.append("spring.jpa.show-sql = true");
    _builder.newLine();
    _builder.append("spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.");
    DatabaseConfiguration _database_3 = config.getDatabase();
    RDBMS _type = null;
    if (_database_3!=null) {
      _type=_database_3.getType();
    }
    String _hibernateDialect = this.getHibernateDialect(_type.toString());
    _builder.append(_hibernateDialect);
    _builder.newLineIfNotEmpty();
    final String propertiesContent = _builder.toString();
    final String pomFilePath = "src/main/resources/application.properties";
    fsa.generateFile(pomFilePath, propertiesContent);
  }

  public void generatePropertiesFile(final ProjectConfiguration config, final IFileSystemAccess2 fsa) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Server Configuration");
    _builder.newLine();
    _builder.append("server.port = ");
    int _xifexpression = (int) 0;
    if ((Objects.equals(config.getServer(), null) || (config.getServer().getPort() == 0))) {
      _xifexpression = 8080;
    } else {
      _xifexpression = config.getServer().getPort();
    }
    _builder.append(_xifexpression);
    _builder.newLineIfNotEmpty();
    _builder.append("server.cpath = ");
    String _elvis = null;
    ServerConfiguration _server = config.getServer();
    String _contextPath = null;
    if (_server!=null) {
      _contextPath=_server.getContextPath();
    }
    if (_contextPath != null) {
      _elvis = _contextPath;
    } else {
      _elvis = "/api";
    }
    _builder.append(_elvis);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Database Configuration");
    _builder.newLine();
    _builder.append("spring.datasource.url = jdbc:");
    Object _elvis_1 = null;
    DatabaseConfiguration _database = config.getDatabase();
    RDBMS _type = null;
    if (_database!=null) {
      _type=_database.getType();
    }
    if (_type != null) {
      _elvis_1 = _type;
    } else {
      _elvis_1 = "mysql";
    }
    _builder.append(_elvis_1);
    _builder.append("://localhost:");
    int _xifexpression_1 = (int) 0;
    if ((Objects.equals(config.getDatabase(), null) || (config.getDatabase().getPort() == 0))) {
      _xifexpression_1 = 3306;
    } else {
      _xifexpression_1 = config.getDatabase().getPort();
    }
    _builder.append(_xifexpression_1);
    _builder.append("/");
    String _elvis_2 = null;
    DatabaseConfiguration _database_1 = config.getDatabase();
    String _name = null;
    if (_database_1!=null) {
      _name=_database_1.getName();
    }
    if (_name != null) {
      _elvis_2 = _name;
    } else {
      _elvis_2 = "dbname";
    }
    _builder.append(_elvis_2);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.username = ");
    String _elvis_3 = null;
    DatabaseConfiguration _database_2 = config.getDatabase();
    String _username = null;
    if (_database_2!=null) {
      _username=_database_2.getUsername();
    }
    if (_username != null) {
      _elvis_3 = _username;
    } else {
      _elvis_3 = "root";
    }
    _builder.append(_elvis_3);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.password = ");
    String _elvis_4 = null;
    DatabaseConfiguration _database_3 = config.getDatabase();
    String _password = null;
    if (_database_3!=null) {
      _password=_database_3.getPassword();
    }
    if (_password != null) {
      _elvis_4 = _password;
    } else {
      _elvis_4 = "password";
    }
    _builder.append(_elvis_4);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# Hibernate Configuration");
    _builder.newLine();
    _builder.append("spring.jpa.hibernate.ddl-auto = update");
    _builder.newLine();
    _builder.append("spring.jpa.show-sql = true");
    _builder.newLine();
    _builder.append("spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.");
    DatabaseConfiguration _database_4 = config.getDatabase();
    RDBMS _type_1 = null;
    if (_database_4!=null) {
      _type_1=_database_4.getType();
    }
    String _hibernateDialect = this.getHibernateDialect(_type_1.toString());
    _builder.append(_hibernateDialect);
    _builder.newLineIfNotEmpty();
    final String propertiesContent = _builder.toString();
    final String pomFilePath = "src/main/resources/application.properties";
    fsa.generateFile(pomFilePath, propertiesContent);
  }

  public void generateMavenFiles(final IFileSystemAccess2 fsa, final Resource input) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.5/apache-maven-3.9.5-bin.zip");
    _builder.newLine();
    _builder.append("wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar");
    _builder.newLine();
    final String pomContent = _builder.toString();
    final String pomFilePath = "mvn/wrapper/maven-wrapper.properties";
    fsa.generateFile(pomFilePath, pomContent);
  }

  public String extractValueType(final String typeString) {
    final String[] parts = typeString.split("\\s+");
    final String vtypesPart = IterableExtensions.<String>last(((Iterable<String>)Conversions.doWrapArray(parts)));
    int _length = vtypesPart.length();
    int _minus = (_length - 1);
    return vtypesPart.substring(0, _minus);
  }

  public void generateTestFolder(final IFileSystemAccess2 fsa, final Resource input) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.junit.jupiter.api.Test;");
    _builder.newLine();
    _builder.append("import org.springframework.boot.test.context.SpringBootTest;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SpringBootTest");
    _builder.newLine();
    _builder.append("class ");
    String _firstUpper = StringExtensions.toFirstUpper(projectName);
    _builder.append(_firstUpper);
    _builder.append("ApplicationTests {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Test");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("void contextLoads() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    final String content2 = _builder.toString();
    String _firstUpper_1 = StringExtensions.toFirstUpper(projectName);
    String _plus = ((("src/test/java/com/springboot/" + projectName) + "/") + _firstUpper_1);
    final String fpath = (_plus + "ApplicationTests.java");
    fsa.generateFile(fpath, content2);
  }

  public void generateMainClass(final IFileSystemAccess2 fsa, final Resource input, final ProjectConfiguration configuration) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(".");
    RDBMS _type = configuration.getDatabase().getType();
    _builder.append(_type);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.boot.SpringApplication;");
    _builder.newLine();
    _builder.append("import org.springframework.boot.autoconfigure.SpringBootApplication;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SpringBootApplication");
    _builder.newLine();
    _builder.append("public class ");
    String _firstUpper = StringExtensions.toFirstUpper(projectName);
    _builder.append(_firstUpper);
    _builder.append("Application {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("SpringApplication.run(");
    String _firstUpper_1 = StringExtensions.toFirstUpper(projectName);
    _builder.append(_firstUpper_1, "        ");
    _builder.append("Application.class, args);");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    final String content2 = _builder.toString();
    String _firstUpper_2 = StringExtensions.toFirstUpper(projectName);
    String _plus = ((("src/main/java/com/springboot/" + projectName) + "/") + _firstUpper_2);
    final String fpath = (_plus + "Application.java");
    fsa.generateFile(fpath, content2);
  }

  public String getSimpleTypeName(final Type type) {
    if ((type instanceof ListType)) {
      String _simpleTypeName = this.getSimpleTypeName(((ListType)type).getType());
      String _plus = ("List<" + _simpleTypeName);
      return (_plus + ">");
    } else {
      if ((type instanceof SetType)) {
        String _simpleTypeName_1 = this.getSimpleTypeName(((SetType)type).getType());
        String _plus_1 = ("Set<" + _simpleTypeName_1);
        return (_plus_1 + ">");
      } else {
        if ((type instanceof ValueTypes)) {
          return ((ValueTypes)type).toString();
        } else {
          return this.extractValueType(type.toString());
        }
      }
    }
  }

  public void generateDtoClass(final DTO dto, final IFileSystemAccess2 fsa, final Resource input) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    final String className = dto.getName();
    final EList<Property> properties = dto.getProperties();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(".DTO;");
    _builder.newLineIfNotEmpty();
    _builder.append("import lombok.*;");
    _builder.newLine();
    _builder.append("import java.util.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Builder");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    {
      for(final Property property : properties) {
        _builder.append("    ");
        _builder.append("private ");
        String _simpleTypeName = this.getSimpleTypeName(property.getType());
        _builder.append(_simpleTypeName, "    ");
        _builder.append(" ");
        String _name = property.getName();
        _builder.append(_name, "    ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    {
      for(final Property property_1 : properties) {
        _builder.append("    ");
        _builder.append("public ");
        String _simpleTypeName_1 = this.getSimpleTypeName(property_1.getType());
        _builder.append(_simpleTypeName_1, "    ");
        _builder.append(" get");
        String _firstUpper = StringExtensions.toFirstUpper(property_1.getName());
        _builder.append(_firstUpper, "    ");
        _builder.append("() {");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("return ");
        String _name_1 = property_1.getName();
        _builder.append(_name_1, "        ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("public void set");
        String _firstUpper_1 = StringExtensions.toFirstUpper(property_1.getName());
        _builder.append(_firstUpper_1, "    ");
        _builder.append("(");
        String _simpleTypeName_2 = this.getSimpleTypeName(property_1.getType());
        _builder.append(_simpleTypeName_2, "    ");
        _builder.append(" ");
        String _name_2 = property_1.getName();
        _builder.append(_name_2, "    ");
        _builder.append(") {");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("this.");
        String _name_3 = property_1.getName();
        _builder.append(_name_3, "        ");
        _builder.append(" = ");
        String _name_4 = property_1.getName();
        _builder.append(_name_4, "        ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("}");
    _builder.newLine();
    final String content = _builder.toString();
    final String folderPath = (("src/main/java/com/springboot/" + projectName) + "/DTO");
    final String filePath = (((folderPath + "/") + className) + ".java");
    fsa.generateFile(filePath, content);
  }

  public void generateRepository(final Entity entity, final IFileSystemAccess2 fsa, final Resource input, final String idType) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field propertyType is undefined for the type FindByMethod"
      + "\nThe method or field propertyType is undefined for the type DeleteByMethod"
      + "\ntoString cannot be resolved"
      + "\ntoString cannot be resolved");
  }

  public void generateEntityClass(final Entity entity, final IFileSystemAccess2 fsa, final Resource input, final String idType, final String idName) {
    final ArrayList<String> projectNameHolder = new ArrayList<String>();
    final Procedure1<EObject> _function = (EObject element) -> {
      if ((element instanceof SpringBootProject)) {
        projectNameHolder.add(((SpringBootProject)element).getName());
      }
    };
    IteratorExtensions.<EObject>forEach(input.getAllContents(), _function);
    final String projectName = projectNameHolder.get(0);
    final String className = entity.getName();
    final EList<Property> properties = entity.getProperties();
    final Entity extendsClause = entity.getExtends();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.springboot.");
    _builder.append(projectName);
    _builder.append(".entities;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Entity;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Table;");
    _builder.newLine();
    _builder.append("import lombok.*;");
    _builder.newLine();
    _builder.append("import java.util.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("@Table(name = \"");
    _builder.append(className);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("@Builder");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className);
    _builder.append(" ");
    {
      if ((extendsClause != null)) {
        _builder.append("extends ");
        _builder.append(extendsClause);
        _builder.append(" ");
      }
    }
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private ");
    _builder.append(idType, "    ");
    _builder.append(" ");
    _builder.append(idName, "    ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    {
      for(final Property property : properties) {
        _builder.append("    ");
        _builder.append("private ");
        String _simpleTypeName = this.getSimpleTypeName(property.getType());
        _builder.append(_simpleTypeName, "    ");
        _builder.append(" ");
        String _name = property.getName();
        _builder.append(_name, "    ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(idType, "    ");
    _builder.append(" get");
    String _firstUpper = StringExtensions.toFirstUpper(idName);
    _builder.append(_firstUpper, "    ");
    _builder.append("() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ");
    _builder.append(idName, "        ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    {
      for(final Property property_1 : properties) {
        _builder.append("    ");
        _builder.append("public ");
        String _simpleTypeName_1 = this.getSimpleTypeName(property_1.getType());
        _builder.append(_simpleTypeName_1, "    ");
        _builder.append(" get");
        String _firstUpper_1 = StringExtensions.toFirstUpper(property_1.getName());
        _builder.append(_firstUpper_1, "    ");
        _builder.append("() {");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("return ");
        String _name_1 = property_1.getName();
        _builder.append(_name_1, "        ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("public void set");
        String _firstUpper_2 = StringExtensions.toFirstUpper(property_1.getName());
        _builder.append(_firstUpper_2, "    ");
        _builder.append("(");
        String _simpleTypeName_2 = this.getSimpleTypeName(property_1.getType());
        _builder.append(_simpleTypeName_2, "    ");
        _builder.append(" ");
        String _name_2 = property_1.getName();
        _builder.append(_name_2, "    ");
        _builder.append(") {");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("    ");
        _builder.append("this.");
        String _name_3 = property_1.getName();
        _builder.append(_name_3, "        ");
        _builder.append(" = ");
        String _name_4 = property_1.getName();
        _builder.append(_name_4, "        ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("}");
    _builder.newLine();
    final String content = _builder.toString();
    final String folderPath = (("src/main/java/com/springboot/" + projectName) + "/entities");
    final String filePath = (((folderPath + "/") + className) + ".java");
    fsa.generateFile(filePath, content);
  }
}
