/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpringGenRuntimeModule extends AbstractSpringGenRuntimeModule {
}
