<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="springgen" nsURI="http://www.xtext.org/example/springgen/springgen"
    nsPrefix="springgen">
  <eClassifiers xsi:type="ecore:EClass" name="SpringBootProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//ProjectConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ProjectElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRelationship" eSuperTypes="#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DatabaseRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//ServerConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//DatabaseConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RDBMS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//Identifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//ValueTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTO" eSuperTypes="#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ServiceAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customActions" upperBound="-1"
        eType="#//CustomAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createParam" eType="#//ParamTransfer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="findParam" eType="#//ParamTransfer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteParam" eType="#//ParamTransfer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//ReturnType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ActionParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//HttpMethods"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ActionParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="findBy" upperBound="-1"
        eType="#//FindByMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteBy" upperBound="-1"
        eType="#//DeleteByMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customQueryMethods" upperBound="-1"
        eType="#//CustomQueryMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FindByMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="#//ValueTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteByMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="#//ValueTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomQueryMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" eType="#//ValueTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnValueType" eType="#//ValueTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="#//Type #//ReturnType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ValueTypes">
    <eLiterals name="FLOAT" literal="float"/>
    <eLiterals name="LONG" value="1" literal="long"/>
    <eLiterals name="INTEGER" value="2" literal="int"/>
    <eLiterals name="CHAR" value="3" literal="char"/>
    <eLiterals name="BOOLEAN" value="4" literal="boolean"/>
    <eLiterals name="BYTE" value="5" literal="byte"/>
    <eLiterals name="STRING" value="6" literal="String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethods">
    <eLiterals name="GET" literal="Get"/>
    <eLiterals name="DELETE" value="1" literal="Delete"/>
    <eLiterals name="POST" value="2" literal="Post"/>
    <eLiterals name="PUT" value="3" literal="Put"/>
    <eLiterals name="PATCH" value="4" literal="Patch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RDBMS">
    <eLiterals name="MYSQL" literal="Mysql"/>
    <eLiterals name="POSTGRES" value="1" literal="Postgres"/>
    <eLiterals name="MARIADB" value="2" literal="Mariadb"/>
    <eLiterals name="H2" value="3" literal="h2"/>
    <eLiterals name="ORACLE" value="4" literal="Oracle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseRelations">
    <eLiterals name="MANY_TO_MANY" literal="ManyToMany"/>
    <eLiterals name="MANY_TO_ONE" value="1" literal="ManyToOne"/>
    <eLiterals name="ONE_TO_MANY" value="2" literal="OneToMany"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParamTransfer">
    <eLiterals name="REQUEST_BODY" literal="RequestBody"/>
    <eLiterals name="REQUEST_PARAM" value="1" literal="RequestParam"/>
    <eLiterals name="PATH_VARIABLE" value="2" literal="PathVariable"/>
  </eClassifiers>
</ecore:EPackage>
