/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.springgen.SpringGenRuntimeModule;
import org.xtext.example.springgen.SpringGenStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SpringGenIdeSetup extends SpringGenStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SpringGenRuntimeModule(), new SpringGenIdeModule()));
	}
	
}
