/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getPort <em>Port</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getUsername <em>Username</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration()
 * @model
 * @generated
 */
public interface DatabaseConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(RDBMS)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration_Type()
   * @model containment="true"
   * @generated
   */
  RDBMS getType();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(RDBMS value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Username</em>' attribute.
   * @see #setUsername(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration_Username()
   * @model
   * @generated
   */
  String getUsername();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getUsername <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Username</em>' attribute.
   * @see #getUsername()
   * @generated
   */
  void setUsername(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseConfiguration_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseConfiguration#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

} // DatabaseConfiguration
