/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database Relations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getM2M <em>M2M</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getM2O <em>M2O</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getO2M <em>O2M</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations()
 * @model
 * @generated
 */
public interface DatabaseRelations extends EObject
{
  /**
   * Returns the value of the '<em><b>M2M</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M2M</em>' attribute.
   * @see #setM2M(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_M2M()
   * @model
   * @generated
   */
  String getM2M();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getM2M <em>M2M</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M2M</em>' attribute.
   * @see #getM2M()
   * @generated
   */
  void setM2M(String value);

  /**
   * Returns the value of the '<em><b>M2O</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M2O</em>' attribute.
   * @see #setM2O(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_M2O()
   * @model
   * @generated
   */
  String getM2O();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getM2O <em>M2O</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M2O</em>' attribute.
   * @see #getM2O()
   * @generated
   */
  void setM2O(String value);

  /**
   * Returns the value of the '<em><b>O2M</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>O2M</em>' attribute.
   * @see #setO2M(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_O2M()
   * @model
   * @generated
   */
  String getO2M();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getO2M <em>O2M</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>O2M</em>' attribute.
   * @see #getO2M()
   * @generated
   */
  void setO2M(String value);

} // DatabaseRelations
