/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database Relations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getMANY_TO_MANY <em>MANY TO MANY</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getMANY_TO_ONE <em>MANY TO ONE</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.DatabaseRelations#getONE_TO_MANY <em>ONE TO MANY</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations()
 * @model
 * @generated
 */
public interface DatabaseRelations extends EObject
{
  /**
   * Returns the value of the '<em><b>MANY TO MANY</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>MANY TO MANY</em>' attribute.
   * @see #setMANY_TO_MANY(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_MANY_TO_MANY()
   * @model
   * @generated
   */
  String getMANY_TO_MANY();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getMANY_TO_MANY <em>MANY TO MANY</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MANY TO MANY</em>' attribute.
   * @see #getMANY_TO_MANY()
   * @generated
   */
  void setMANY_TO_MANY(String value);

  /**
   * Returns the value of the '<em><b>MANY TO ONE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>MANY TO ONE</em>' attribute.
   * @see #setMANY_TO_ONE(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_MANY_TO_ONE()
   * @model
   * @generated
   */
  String getMANY_TO_ONE();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getMANY_TO_ONE <em>MANY TO ONE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MANY TO ONE</em>' attribute.
   * @see #getMANY_TO_ONE()
   * @generated
   */
  void setMANY_TO_ONE(String value);

  /**
   * Returns the value of the '<em><b>ONE TO MANY</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ONE TO MANY</em>' attribute.
   * @see #setONE_TO_MANY(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getDatabaseRelations_ONE_TO_MANY()
   * @model
   * @generated
   */
  String getONE_TO_MANY();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.DatabaseRelations#getONE_TO_MANY <em>ONE TO MANY</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ONE TO MANY</em>' attribute.
   * @see #getONE_TO_MANY()
   * @generated
   */
  void setONE_TO_MANY(String value);

} // DatabaseRelations
