/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getExtends <em>Extends</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getRepository <em>Repository</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getServices <em>Services</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Entity#getController <em>Controller</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends ProjectElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Extends</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extends</em>' reference.
   * @see #setExtends(Entity)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Extends()
   * @model
   * @generated
   */
  Entity getExtends();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.Entity#getExtends <em>Extends</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extends</em>' reference.
   * @see #getExtends()
   * @generated
   */
  void setExtends(Entity value);

  /**
   * Returns the value of the '<em><b>Identifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' containment reference.
   * @see #setIdentifier(Identifier)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Identifier()
   * @model containment="true"
   * @generated
   */
  Identifier getIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.Entity#getIdentifier <em>Identifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' containment reference.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(Identifier value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

  /**
   * Returns the value of the '<em><b>Repository</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repository</em>' containment reference.
   * @see #setRepository(Repository)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Repository()
   * @model containment="true"
   * @generated
   */
  Repository getRepository();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.Entity#getRepository <em>Repository</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repository</em>' containment reference.
   * @see #getRepository()
   * @generated
   */
  void setRepository(Repository value);

  /**
   * Returns the value of the '<em><b>Services</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.Service}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Services</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Services()
   * @model containment="true"
   * @generated
   */
  EList<Service> getServices();

  /**
   * Returns the value of the '<em><b>Controller</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller</em>' containment reference.
   * @see #setController(Controller)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getEntity_Controller()
   * @model containment="true"
   * @generated
   */
  Controller getController();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.Entity#getController <em>Controller</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller</em>' containment reference.
   * @see #getController()
   * @generated
   */
  void setController(Controller value);

} // Entity
