/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Transfer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.ParamTransfer#getREQUEST_BODY <em>REQUEST BODY</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.ParamTransfer#getREQUEST_PARAM <em>REQUEST PARAM</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.ParamTransfer#getPATH_VARIABLE <em>PATH VARIABLE</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getParamTransfer()
 * @model
 * @generated
 */
public interface ParamTransfer extends EObject
{
  /**
   * Returns the value of the '<em><b>REQUEST BODY</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>REQUEST BODY</em>' attribute.
   * @see #setREQUEST_BODY(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getParamTransfer_REQUEST_BODY()
   * @model
   * @generated
   */
  String getREQUEST_BODY();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.ParamTransfer#getREQUEST_BODY <em>REQUEST BODY</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>REQUEST BODY</em>' attribute.
   * @see #getREQUEST_BODY()
   * @generated
   */
  void setREQUEST_BODY(String value);

  /**
   * Returns the value of the '<em><b>REQUEST PARAM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>REQUEST PARAM</em>' attribute.
   * @see #setREQUEST_PARAM(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getParamTransfer_REQUEST_PARAM()
   * @model
   * @generated
   */
  String getREQUEST_PARAM();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.ParamTransfer#getREQUEST_PARAM <em>REQUEST PARAM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>REQUEST PARAM</em>' attribute.
   * @see #getREQUEST_PARAM()
   * @generated
   */
  void setREQUEST_PARAM(String value);

  /**
   * Returns the value of the '<em><b>PATH VARIABLE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PATH VARIABLE</em>' attribute.
   * @see #setPATH_VARIABLE(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getParamTransfer_PATH_VARIABLE()
   * @model
   * @generated
   */
  String getPATH_VARIABLE();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.ParamTransfer#getPATH_VARIABLE <em>PATH VARIABLE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PATH VARIABLE</em>' attribute.
   * @see #getPATH_VARIABLE()
   * @generated
   */
  void setPATH_VARIABLE(String value);

} // ParamTransfer
