/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getProjectElement()
 * @model
 * @generated
 */
public interface ProjectElement extends EObject
{
} // ProjectElement
