/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getFindByMethods <em>Find By Methods</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getDeleteByMethods <em>Delete By Methods</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getCustomQueryMethods <em>Custom Query Methods</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository()
 * @model
 * @generated
 */
public interface Repository extends ProjectElement
{
  /**
   * Returns the value of the '<em><b>Find By Methods</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.FindByMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Find By Methods</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_FindByMethods()
   * @model containment="true"
   * @generated
   */
  EList<FindByMethod> getFindByMethods();

  /**
   * Returns the value of the '<em><b>Delete By Methods</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.DeleteByMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete By Methods</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_DeleteByMethods()
   * @model containment="true"
   * @generated
   */
  EList<DeleteByMethod> getDeleteByMethods();

  /**
   * Returns the value of the '<em><b>Custom Query Methods</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.CustomQueryMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Query Methods</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_CustomQueryMethods()
   * @model containment="true"
   * @generated
   */
  EList<CustomQueryMethod> getCustomQueryMethods();

} // Repository
