/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repository</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getFindBy <em>Find By</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getDeleteBy <em>Delete By</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.Repository#getCustomQueryMethod <em>Custom Query Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository()
 * @model
 * @generated
 */
public interface Repository extends ProjectElement
{
  /**
   * Returns the value of the '<em><b>Find By</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.FindByMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Find By</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_FindBy()
   * @model containment="true"
   * @generated
   */
  EList<FindByMethod> getFindBy();

  /**
   * Returns the value of the '<em><b>Delete By</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.DeleteByMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete By</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_DeleteBy()
   * @model containment="true"
   * @generated
   */
  EList<DeleteByMethod> getDeleteBy();

  /**
   * Returns the value of the '<em><b>Custom Query Method</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.springgen.springgen.CustomQueryMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Query Method</em>' containment reference list.
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getRepository_CustomQueryMethod()
   * @model containment="true"
   * @generated
   */
  EList<CustomQueryMethod> getCustomQueryMethod();

} // Repository
