/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Server Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.springgen.springgen.ServerConfiguration#getPort <em>Port</em>}</li>
 *   <li>{@link org.xtext.example.springgen.springgen.ServerConfiguration#getContextPath <em>Context Path</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.springgen.springgen.SpringgenPackage#getServerConfiguration()
 * @model
 * @generated
 */
public interface ServerConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getServerConfiguration_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.ServerConfiguration#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Context Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Path</em>' attribute.
   * @see #setContextPath(String)
   * @see org.xtext.example.springgen.springgen.SpringgenPackage#getServerConfiguration_ContextPath()
   * @model
   * @generated
   */
  String getContextPath();

  /**
   * Sets the value of the '{@link org.xtext.example.springgen.springgen.ServerConfiguration#getContextPath <em>Context Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Path</em>' attribute.
   * @see #getContextPath()
   * @generated
   */
  void setContextPath(String value);

} // ServerConfiguration
