/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.springgen.springgen;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.springgen.springgen.SpringgenPackage
 * @generated
 */
public interface SpringgenFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpringgenFactory eINSTANCE = org.xtext.example.springgen.springgen.impl.SpringgenFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Spring Boot Project</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spring Boot Project</em>'.
   * @generated
   */
  SpringBootProject createSpringBootProject();

  /**
   * Returns a new object of class '<em>Project Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project Element</em>'.
   * @generated
   */
  ProjectElement createProjectElement();

  /**
   * Returns a new object of class '<em>Entity Relationship</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Relationship</em>'.
   * @generated
   */
  EntityRelationship createEntityRelationship();

  /**
   * Returns a new object of class '<em>Project Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Project Configuration</em>'.
   * @generated
   */
  ProjectConfiguration createProjectConfiguration();

  /**
   * Returns a new object of class '<em>Server Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server Configuration</em>'.
   * @generated
   */
  ServerConfiguration createServerConfiguration();

  /**
   * Returns a new object of class '<em>Database Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Database Configuration</em>'.
   * @generated
   */
  DatabaseConfiguration createDatabaseConfiguration();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Identifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Identifier</em>'.
   * @generated
   */
  Identifier createIdentifier();

  /**
   * Returns a new object of class '<em>DTO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DTO</em>'.
   * @generated
   */
  DTO createDTO();

  /**
   * Returns a new object of class '<em>Service</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Service</em>'.
   * @generated
   */
  Service createService();

  /**
   * Returns a new object of class '<em>Controller</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Controller</em>'.
   * @generated
   */
  Controller createController();

  /**
   * Returns a new object of class '<em>Service Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Service Action</em>'.
   * @generated
   */
  ServiceAction createServiceAction();

  /**
   * Returns a new object of class '<em>Custom Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom Action</em>'.
   * @generated
   */
  CustomAction createCustomAction();

  /**
   * Returns a new object of class '<em>Action Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Parameter</em>'.
   * @generated
   */
  ActionParameter createActionParameter();

  /**
   * Returns a new object of class '<em>Repository</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repository</em>'.
   * @generated
   */
  Repository createRepository();

  /**
   * Returns a new object of class '<em>Find By Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Find By Method</em>'.
   * @generated
   */
  FindByMethod createFindByMethod();

  /**
   * Returns a new object of class '<em>Delete By Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete By Method</em>'.
   * @generated
   */
  DeleteByMethod createDeleteByMethod();

  /**
   * Returns a new object of class '<em>Custom Query Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom Query Method</em>'.
   * @generated
   */
  CustomQueryMethod createCustomQueryMethod();

  /**
   * Returns a new object of class '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property</em>'.
   * @generated
   */
  Property createProperty();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Return Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Return Type</em>'.
   * @generated
   */
  ReturnType createReturnType();

  /**
   * Returns a new object of class '<em>List Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Type</em>'.
   * @generated
   */
  ListType createListType();

  /**
   * Returns a new object of class '<em>Set Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Type</em>'.
   * @generated
   */
  SetType createSetType();

  /**
   * Returns a new object of class '<em>Value Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value Types</em>'.
   * @generated
   */
  ValueTypes createValueTypes();

  /**
   * Returns a new object of class '<em>Http Methods</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Http Methods</em>'.
   * @generated
   */
  HttpMethods createHttpMethods();

  /**
   * Returns a new object of class '<em>RDBMS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RDBMS</em>'.
   * @generated
   */
  RDBMS createRDBMS();

  /**
   * Returns a new object of class '<em>Database Relations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Database Relations</em>'.
   * @generated
   */
  DatabaseRelations createDatabaseRelations();

  /**
   * Returns a new object of class '<em>Param Transfer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Param Transfer</em>'.
   * @generated
   */
  ParamTransfer createParamTransfer();

  /**
   * Returns a new object of class '<em>Dockerfile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dockerfile</em>'.
   * @generated
   */
  Dockerfile createDockerfile();

  /**
   * Returns a new object of class '<em>Base Image</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Base Image</em>'.
   * @generated
   */
  BaseImage createBaseImage();

  /**
   * Returns a new object of class '<em>Docker Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Docker Instruction</em>'.
   * @generated
   */
  DockerInstruction createDockerInstruction();

  /**
   * Returns a new object of class '<em>Run Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Run Instruction</em>'.
   * @generated
   */
  RunInstruction createRunInstruction();

  /**
   * Returns a new object of class '<em>Copy Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copy Instruction</em>'.
   * @generated
   */
  CopyInstruction createCopyInstruction();

  /**
   * Returns a new object of class '<em>Expose Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expose Instruction</em>'.
   * @generated
   */
  ExposeInstruction createExposeInstruction();

  /**
   * Returns a new object of class '<em>Env Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Env Instruction</em>'.
   * @generated
   */
  EnvInstruction createEnvInstruction();

  /**
   * Returns a new object of class '<em>Workdir Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workdir Instruction</em>'.
   * @generated
   */
  WorkdirInstruction createWorkdirInstruction();

  /**
   * Returns a new object of class '<em>Cmd Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cmd Instruction</em>'.
   * @generated
   */
  CmdInstruction createCmdInstruction();

  /**
   * Returns a new object of class '<em>Angular App</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular App</em>'.
   * @generated
   */
  AngularApp createAngularApp();

  /**
   * Returns a new object of class '<em>Angular Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular Component</em>'.
   * @generated
   */
  AngularComponent createAngularComponent();

  /**
   * Returns a new object of class '<em>Angular Service</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular Service</em>'.
   * @generated
   */
  AngularService createAngularService();

  /**
   * Returns a new object of class '<em>Angular Service Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular Service Method</em>'.
   * @generated
   */
  AngularServiceMethod createAngularServiceMethod();

  /**
   * Returns a new object of class '<em>Angular Module</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular Module</em>'.
   * @generated
   */
  AngularModule createAngularModule();

  /**
   * Returns a new object of class '<em>Angular Module Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angular Module Import</em>'.
   * @generated
   */
  AngularModuleImport createAngularModuleImport();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SpringgenPackage getSpringgenPackage();

} //SpringgenFactory
